// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace LongPollingBot.Migrations
{

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class multiplerooms : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(multiplerooms));
        
        string IMigrationMetadata.Id
        {
            get { return "201611111429495_multiplerooms"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
